# -*- coding: utf-8 -*-
"""Assignment 5.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/148iFu4QLkofkOxI5jdB0DyLOaw36QqWp
Assignment 5
"""
#python -m pip install --upgrade pip


import streamlit as st
import urllib.request
import whisper
from pytube import YouTube

from tqdm.auto import tqdm
from time import sleep

from youtube_transcript_api import YouTubeTranscriptApi
import openai
import pinecone


st.title("Welcome")

query = st.text_input("How can I assist you today?")
youtube_video_url='https://www.youtube.com/watch?v=tmGDx9hVWwo'

youtube=YouTube(youtube_video_url)

duration=youtube.length

yt_title = youtube.title

yt_channel_id=youtube.channel_id

yt_video_id=youtube.video_id

youtube.from_id

streams=youtube.streams.filter(only_audio=True)
stream=streams.first()
stream
