# -*- coding: utf-8 -*-
"""Assignment 5.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/148iFu4QLkofkOxI5jdB0DyLOaw36QqWp
Assignment 5
"""
#python -m pip install --upgrade pip


import streamlit as st
import urllib.request
import whisper
from pytube import YouTube

from tqdm.auto import tqdm
from time import sleep

from youtube_transcript_api import YouTubeTranscriptApi
import openai
import pinecone


st.title("Welcome")

query = st.text_input("How can I assist you today?")
